# Generated by Django 4.1.7 on 2023-04-26 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customeruser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='birth_date',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='gender',
            field=models.CharField(choices=[('М', 'Мужчина'), ('Ж', 'Женщина')], max_length=7, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='middle_name',
            field=models.CharField(max_length=130, verbose_name='Отчество'),
        ),
    ]
