# Generated by Django 4.1.7 on 2023-04-26 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customeruser_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='gender',
            field=models.CharField(choices=[('М', 'Мужчина'), ('Ж', 'Женщина')], default='', max_length=7, verbose_name='Пол'),
        ),
    ]
