# Generated by Django 4.1.7 on 2023-04-26 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_customeruser_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='gender',
            field=models.CharField(blank=True, choices=[('М', 'Мужчина'), ('Ж', 'Женщина')], max_length=7, null=True, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='middle_name',
            field=models.CharField(blank=True, max_length=130, null=True, verbose_name='Отчество'),
        ),
    ]
